### ISSUE TITLE
Cannot connect

### ISSUE THREAD

**Issue by Vetti52** [wuwentao/midea_ac_lan#276] opened 2024-08-13 14:53 UTC
### HA core version

2024.2.2

### Current integration version

0.5.5

### Last known working integration version

0.5.3

### Device type and model

Dehumidifier 00000Q1A (161)

### Working mobile app

Home Assisstant

### The description of problem

When unpowering the dehumidifier (e.g. by a switching plug), the connection to HA is lost and will not reconnect, when power is established again.

### The logs

[homeassistant.loader] We found a custom integration midea_ac_lan which has not been tested by Home Assistant. This component might cause stability
problems, be sure to disable it if you experience issues with Home Assistant
2024-08-11 06:30:27.100 ERROR (Luftentfeuchter) [root] Uncaught thread exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/site-packages/midealocal/device.py", line 515, in run
    raise CannotConnect
midealocal.exceptions.CannotConnect

**Comment by chemelli74** [comment] 2024-08-13 15:12
Thx for opening this issue.

As discussed via Discord, we will reap this and add a ConfigNotReady to make the integration retry in background.

**Comment by mag1024** [comment] 2024-08-16 04:24
This is still happening with 0.5.7.
The last version that worked reliably was 0.5.4

**Comment by Vetti52** [comment] 2024-08-16 08:44
Same with version 0.5.7.

**Comment by chemelli74** [comment] 2024-08-16 16:25
Will fix it in the correct and final way more or less in the end of August when I'm back from my vacations

**Comment by grigi** [comment] 2024-08-25 14:35
I have the exact same issue. downgrading to 0.5.3 fixed everything for me again.

**Comment by chemelli74** [comment] 2024-08-30 09:53
Please enable [Debug](https://www.home-assistant.io/docs/configuration/troubleshooting/#enabling-debug-logging) for Midea AC Lan integration, wait for this error, disable debug and attach the log.

Note: it is better to drag the log into the comment (which will add it as an attachment) and not copy paste as it is hard to read logs in GitHub.

Thanks

**Comment by lyfqdl** [comment] 2024-08-30 16:10
同样的问题。路由器重启后，设备实体不可用，除非手动重新加载。

**Comment by chemelli74** [comment] 2024-08-30 17:12
Please don't comment same problem, instead provide required log

**Comment by mag1024** [comment] 2024-08-30 18:02
I think it's an issue with the `midealocal` library.
It does a thread start in `device.open` [here](https://github.com/rokam/midea-local/blob/8610f1e1b728e1c87be81ed2bfa109256c173bc1/midealocal/device.py#L491C1-L492C1), but if the connection fails, the [thrown](https://github.com/rokam/midea-local/blob/8610f1e1b728e1c87be81ed2bfa109256c173bc1/midealocal/device.py#L532) `CannotConnect` is never caught, causing the thread to exit, and the device to be left in an unconnected state.

**Comment by chemelli74** [comment] 2024-08-30 18:27
Guys, if you want a fix attach debug log.

**Comment by xiasi0** [comment] 2024-09-04 17:34
+1风扇设备同样情况

**Comment by wuwentao** [comment] 2024-09-06 05:30
@xiasi0 @lo00l @mag1024 @lyfqdl @grigi @Vetti52 

Hi all, 

This is a known issue for a long time, and we want to fix it and cover most of the errors, @mag1024 also found the code changes,  @chemelli74 want to fix some connection issue, so we need to confirm the error info via the full debug log file.

but most of us don't want to upload the debug log file and just report the issue, or paste some lines log in issue.
could you help to upload your full debug log file for bug and connection process analyze?
we will fix it in some days.

thanks

**Comment by phidauex** [comment] 2024-09-06 15:51
Possible duplicate of #306 .

Attached is full log file and relevant excerpt

[home-assistant.log](https://github.com/user-attachments/files/16910261/home-assistant.log)

```
2024-09-04 10:09:10.986 DEBUG (Dehumidifier) [midealocal.devices.a1] [150633093756827] Received: {'header': 'aa23a100000000000803', 'body': 'c80101287f7f003700000000000000643c5c00000000001f72', 'message type': '.03', 'body type': '.c8'}
2024-09-04 10:09:10.986 DEBUG (Dehumidifier) [midealocal.devices.a1] Device - tank: 0, tank_full: False,                                      water_level: 100, tank_full_calculated: False
2024-09-04 10:09:10.986 DEBUG (Dehumidifier) [midealocal.devices.a1] Device after - new_status: {'power': True}, tank_full: False
2024-09-04 10:09:10.986 DEBUG (Dehumidifier) [midealocal.devices.a1] Device - tank: 0, tank_full: False,                                      water_level: 100, tank_full_calculated: False
2024-09-04 10:09:10.986 DEBUG (Dehumidifier) [midealocal.devices.a1] Device after - new_status: {'power': True, 'child_lock': False}, tank_full: False
2024-09-04 10:09:10.986 DEBUG (Dehumidifier) [midealocal.devices.a1] Device - tank: 0, tank_full: False,                                      water_level: 100, tank_full_calculated: False
2024-09-04 10:09:10.986 DEBUG (Dehumidifier) [midealocal.devices.a1] Device after - new_status: {'power': True, 'child_lock': False, 'mode': 'Manual'}, tank_full: False
2024-09-04 10:09:10.986 DEBUG (Dehumidifier) [midealocal.devices.a1] Device - tank: 0, tank_full: False,                                      water_level: 100, tank_full_calculated: False
2024-09-04 10:09:10.986 DEBUG (Dehumidifier) [midealocal.devices.a1] Device after - new_status: {'power': True, 'child_lock': False, 'mode': 'Manual', 'fan_speed': 'Low'}, tank_full: False
2024-09-04 10:09:10.986 DEBUG (Dehumidifier) [midealocal.devices.a1] Device - tank: 0, tank_full: False,                                      water_level: 100, tank_full_calculated: False
2024-09-04 10:09:10.986 DEBUG (Dehumidifier) [midealocal.devices.a1] Device after - new_status: {'power': True, 'child_lock': False, 'mode': 'Manual', 'fan_speed': 'Low', 'swing': False}, tank_full: False
2024-09-04 10:09:10.986 DEBUG (Dehumidifier) [midealocal.devices.a1] Device - tank: 0, tank_full: False,                                      water_level: 100, tank_full_calculated: False
2024-09-04 10:09:10.986 DEBUG (Dehumidifier) [midealocal.devices.a1] Device after - new_status: {'power': True, 'child_lock': False, 'mode': 'Manual', 'fan_speed': 'Low', 'swing': False, 'target_humidity': 55}, tank_full: False
2024-09-04 10:09:10.986 DEBUG (Dehumidifier) [midealocal.devices.a1] Device - tank: 0, tank_full: False,                                      water_level: 100, tank_full_calculated: False
2024-09-04 10:09:10.986 DEBUG (Dehumidifier) [midealocal.devices.a1] Device after - new_status: {'power': True, 'child_lock': False, 'mode': 'Manual', 'fan_speed': 'Low', 'swing': False, 'target_humidity': 55, 'anion': False}, tank_full: False
2024-09-04 10:09:10.986 DEBUG (Dehumidifier) [midealocal.devices.a1] Device - tank: 0, tank_full: False,                                      water_level: 100, tank_full_calculated: False
2024-09-04 10:09:10.986 DEBUG (Dehumidifier) [midealocal.devices.a1] Device after - new_status: {'power': True, 'child_lock': False, 'mode': 'Manual', 'fan_speed': 'Low', 'swing': False, 'target_humidity': 55, 'anion': False, 'tank': 0}, tank_full: False
2024-09-04 10:09:10.986 DEBUG (Dehumidifier) [midealocal.devices.a1] Device - tank: 0, tank_full: False,                                      water_level: 100, tank_full_calculated: False
2024-09-04 10:09:10.986 DEBUG (Dehumidifier) [midealocal.devices.a1] Device after - new_status: {'power': True, 'child_lock': False, 'mode': 'Manual', 'fan_speed': 'Low', 'swing': False, 'target_humidity': 55, 'anion': False, 'tank': 0, 'water_level_set': '100'}, tank_full: False
2024-09-04 10:09:10.986 DEBUG (Dehumidifier) [midealocal.devices.a1] Device - tank: 0, tank_full: False,                                      water_level: 100, tank_full_calculated: False
2024-09-04 10:09:10.986 DEBUG (Dehumidifier) [midealocal.devices.a1] Device after - new_status: {'power': True, 'child_lock': False, 'mode': 'Manual', 'fan_speed': 'Low', 'swing': False, 'target_humidity': 55, 'anion': False, 'tank': 0, 'water_level_set': '100', 'current_humidity': 60}, tank_full: False
2024-09-04 10:09:10.986 DEBUG (Dehumidifier) [midealocal.devices.a1] Device - tank: 0, tank_full: False,                                      water_level: 100, tank_full_calculated: False
2024-09-04 10:09:10.986 DEBUG (Dehumidifier) [midealocal.devices.a1] Device after - new_status: {'power': True, 'child_lock': False, 'mode': 'Manual', 'fan_speed': 'Low', 'swing': False, 'target_humidity': 55, 'anion': False, 'tank': 0, 'water_level_set': '100', 'current_humidity': 60, 'current_temperature': 21.0}, tank_full: False
2024-09-04 10:09:10.987 DEBUG (Dehumidifier) [midealocal.device] [150633093756827] Status update: {'power': True, 'child_lock': False, 'mode': 'Manual', 'fan_speed': 'Low', 'swing': False, 'target_humidity': 55, 'anion': False, 'tank': 0, 'water_level_set': '100', 'current_humidity': 60, 'current_temperature': 21.0}
2024-09-04 10:09:41.043 DEBUG (Dehumidifier) [midealocal.device] [150633093756827] Sending: {'header': 'aa20a100000000000803', 'body': '418100ff0000000000000000000000000000000020d6', 'message type': '.03', 'body type': '.41'}
2024-09-04 10:10:11.075 DEBUG (Dehumidifier) [midealocal.device] [150633093756827] Sending: {'header': 'aa20a100000000000803', 'body': '418100ff000000000000000000000000000000002188', 'message type': '.03', 'body type': '.41'}
2024-09-04 10:10:41.108 DEBUG (Dehumidifier) [midealocal.device] [150633093756827] Sending: {'header': 'aa20a100000000000803', 'body': '418100ff00000000000000000000000000000000226a', 'message type': '.03', 'body type': '.41'}
2024-09-04 10:11:11.142 DEBUG (Dehumidifier) [midealocal.device] [150633093756827] Heartbeat timed out
2024-09-04 10:11:11.142 DEBUG (Dehumidifier) [midealocal.device] [150633093756827] Connecting to 10.0.20.66:6444
2024-09-04 10:11:21.152 DEBUG (Dehumidifier) [midealocal.device] [150633093756827] Connection timed out
2024-09-04 10:11:21.153 DEBUG (Dehumidifier) [midealocal.device] [150633093756827] Connecting to 10.0.20.66:6444
2024-09-04 10:11:31.163 DEBUG (Dehumidifier) [midealocal.device] [150633093756827] Connection timed out
2024-09-04 10:11:31.163 DEBUG (Dehumidifier) [midealocal.device] [150633093756827] Connecting to 10.0.20.66:6444
2024-09-04 10:11:41.174 DEBUG (Dehumidifier) [midealocal.device] [150633093756827] Connection timed out
2024-09-04 10:11:41.174 DEBUG (Dehumidifier) [midealocal.device] [150633093756827] Enabling device
2024-09-04 10:11:41.174 DEBUG (Dehumidifier) [midealocal.device] [150633093756827] Status update: {'available': False}
2024-09-04 10:11:41.175 ERROR (Dehumidifier) [root] Uncaught thread exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/site-packages/midealocal/device.py", line 515, in run
    raise CannotConnect
midealocal.exceptions.CannotConnect
```

**Comment by wuwentao** [comment] 2024-09-20 15:19
@Vetti52 @mag1024 @grigi  @lyfqdl @lo00l @xiasi0 @phidauex 
it should be fix with latest release v0.5.8, please upgrade and confirm the result.
close current issue, if the same issue still exist, we can continue update in current issue or reopen it later.

**Closed by wuwentao** 2024-09-20 15:19 UTC
Labels: bug, midea-local library

**Comment by lyfqdl** [comment] 2024-09-21 01:15
更新0.58版本后，不会再断联不可用，但空调室内温度，冰箱温度等不再变化。貌似不会更新数据。

**Comment by grigi** [comment] 2024-09-21 12:41
Updating  to 0.5.8 did not resolve my issue either. Last version that works for me is 0.5.4.
My symptom is that it refuses to connect.

**Comment by wuwentao** [comment] 2024-09-21 14:15
> Updating to 0.5.8 did not resolve my issue either. Last version that works for me is 0.5.4. My symptom is that it refuses to connect.

yes, this is a process change issue by chemelli74,  socket exception can't be catch and caused error, but don't worry, we should accept bug and error in feature changes,  and we will try to fix it.

v0.5.8 have a high cpu issue, v0.5.9 is pending and waitting for approve, once it done , new version will available.
