### ISSUE TITLE
希望增加扫地机识别

### ISSUE THREAD

**Issue by tufeikafei** [wuwentao/midea_ac_lan#248] opened 2024-07-19 16:15 UTC
### 设备类型及型号 (或SN)

0000B8511750004D846144XXXXXXXXXX

### 新功能的描述

我尝试修改了代码，但是直接提示没有 token，无奈了，希望增加扫地机状态，以及启动，回充电。

**Comment by rokam** [comment] 2024-07-20 15:23
B8 device support is on the way.
https://github.com/rokam/midea-local/pull/225

We're refactoring the config_flow and token retrieval process. This is blocking the development of this type of device inside the integration. 

Also dupe of #205

**Closed** 2024-07-20 20:25 UTC
Labels: enhancement, midea-local library
